CREATE TABLE IF NOT EXISTS Details
(
	id INT(11) AUTO_INCREMENT,
	Name varchar(255) NOT NULL,
	Nationality varchar(255) NOT NULL,
	National_Position varchar(255),
	National_Kit varchar(255),
	Club varchar(255) NOT NULL, 
	Club_Position varchar(255) NOT NULL,
	Club_Kit  INT(11) NOT NULL,
	Club_Joining date not NULL,
	Contract_Expiry	Rating INT(11) NOT NULL,
	Rating INT(11) NOT NULL,
	Height varchar(255) NOT NULL,
	Weight varchar(255) NOT NULL,
	Preffered_Foot varchar(255) NOT NULL,
	Birth_Date date not NULL,
	Age INT(11) NOT NULL,
	Preffered_Position varchar(255) NOT NULL,
	Work_Rate  varchar(255) NOT NULL,
	Weak_foot INT(11) NOT NULL,
	Skill_Moves INT(11) NOT NULL,	Ball_Control INT(11) NOT NULL,
	Dribbling INT(11) NOT NULL,
	Marking INT(11) NOT NULL,
	Sliding_Tackle INT(11) NOT NULL,
	Standing_Tackle INT(11) NOT NULL,
	Aggression INT(11) NOT NULL,
	Reactions INT(11) NOT NULL,
	Attacking_Position INT(11) NOT NULL,
	Interceptions INT(11) NOT NULL,
	Vision INT(11) NOT NULL,
	Composure INT(11) NOT NULL,
	Crossing INT(11) NOT NULL,
	Short_Pass INT(11) NOT NULL,
	Long_Pass INT(11) NOT NULL,
	Acceleration INT(11) NOT NULL,
	Speed INT(11) NOT NULL,
	Stamina INT(11) NOT NULL,
	Strength INT(11) NOT NULL,
	Balance INT(11) NOT NULL,
	Agility INT(11) NOT NULL,
	Jumping INT(11) NOT NULL,
	Heading INT(11) NOT NULL,
	Shot_Power INT(11) NOT NULL,
	Finish INT(11) NOT NULL,
	Long_Shots INT(11) NOT NULL,
	Curve INT(11) NOT NULL,
	Freekick_Accuracy INT(11) NOT NULL,
	Penalties INT(11) NOT NULL,
	Volleys INT(11) NOT NULL,
	GK_Positioning INT(11) NOT NULL,
	GK_Diving INT(11) NOT NULL,
	GK_Kicking INT(11) NOT NULL,
	GK_Handling INT(11) NOT NULL,
	GK_Reflexes INT(11) NOT NULL,
	PRIMARY KEY (id)
);

